# Configuration file for Read the Docs
#
# https://docs.readthedocs.io/en/stable/config-file/index.html#

version: 2

formats:
  - htmlzip

python:
  version: 3.7
  install:
    - requirements: requirements/install.txt
    - requirements: requirements/docs.txt
    - method: setuptools
      path: .
  system_packages: true
