# Configuration file for Read the Docs
#
# https://docs.readthedocs.io/en/stable/config-file/index.html#

version: 2

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  apt_packages:
  - graphviz

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
