# Configuration file for Read the Docs
#
# https://docs.readthedocs.io/en/stable/config-file/index.html#

version: 2

formats:
  - htmlzip

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extras_requirements:
        - docs
  system_packages: true
