# This file is part of the bapsflib package, a Python toolkit for the
# BaPSF group at UCLA.
#
# http://plasma.physics.ucla.edu/
#
# Copyright 2017-2020 Erik T. Everson and contributors
#
# License: Standard 3-clause BSD; see "LICENSES/LICENSE.txt" for full
#   license terms and contributor agreement.
#
#
# Configuration for Travis CI
#
# languages
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  - osx
  - windows

# The number of commits cloned.  Setting to false will clone all commits.
# Since __version__ is defined with setuptools_scm, the default depth of 50
# could be insufficient.
git:
  depth: false

jobs:
  fast_finish: true

# install dependencies
install:
  - pip install -r requirements.txt

# define test script to run
script:
  - coverage run -m unittest discover

# assess coverage
after_success:
  - codecov
