# This file is part of the bapsflib package, a Python toolkit for the
# BaPSF group at UCLA.
#
# http://plasma.physics.ucla.edu/
#
# Copyright 2017 Erik T. Everson and contributors
#
# License:
#

import h5py
import os
import sys

from .hdferrors import *


class hdfCheck(object):
    _hdf_lapd_version = ''
    _msi_group = 'MSI'
    _msi_diagnostic_groups = ['Discharge', 'Gas pressure', 'Heater',
                              'Interferometer array', 'Magnetic field']
    _data_group = 'Raw data + config'
    _print_tab_len = 35

    def __init__(self, hdf_obj):
        if isinstance(hdf_obj, h5py.File):
            self._hdf_obj = hdf_obj
        else:
            raise NotHDFFileError

        self.full_check()

    def full_check(self):
        """
            Run all pre-defined file checks.

            :return:
        """
        self.is_lapd_generated()
        status = self.exist_msi()
        if status:
            self.exist_msi_diagnostics_all()
        self.check_data_group()

    def is_lapd_generated(self, silent=False):
        """
            Checks the loaded HDF5 file to see if it was generated by
            the LaPD Control System.

            :param silent:
            :return:
        """
        if silent:
            sys.stdout = open(os.devnull, 'w')

        str_print = 'Generated by LaPD '

        is_lapd = False
        for key in self._hdf_obj.attrs.keys():
            if 'lapd' in key.casefold() and 'version' in key.casefold():
                self._hdf_lapd_version = \
                    self._hdf_obj.attrs[key].decode('utf-8')
                is_lapd = True
                break

        if is_lapd:
            str_print += ' yes'.rjust(self._print_tab_len - 1
                                      - str_print.__len__(), '~')
            str_print += '  (v{})'.format(self._hdf_lapd_version)
        else:
            str_print += ' no'.rjust(self._print_tab_len - 1
                                     - str_print.__len__(), '~')
            raise NotLaPDHDFError

        print(str_print + '\n')

        if silent:
            sys.stdout = sys.__stdout__

        return is_lapd, self._hdf_lapd_version

    def exist_msi(self, silent=False):
        """
            Check for the existence of the MSI Group.

            :param silent:
            :return:
        """
        if silent:
            sys.stdout = open(os.devnull, 'w')

        msi_detected = False
        for key in self._hdf_obj.keys():
            if key.casefold() == self._msi_group.casefold():
                msi_detected = True

        str_msi = self._msi_group + '/ '
        if msi_detected:
            str_msi += ' yes'.rjust(self._print_tab_len - 1
                                    - str_msi.__len__(), '~')
            print(str_msi, flush=True)
        else:
            str_msi += 'no'.rjust(self._print_tab_len - 1
                                  - str_msi.__len__(), '~')
            print(str_msi, flush=True)

            raise NoMSIError

        if silent:
            sys.stdout = sys.__stdout__

        return msi_detected

    def exist_msi_diagnostic(self, diag_group_name, silent=False):
        """
            Check for an MSI diagnostc group by the name of
            diag_group_name.

            :param diag_group_name
            :param silent:
            :return:
        """
        if silent:
            sys.stdout = open(os.devnull, 'w')

        diag_detected = False

        for key in self._hdf_obj[self._msi_group].keys():
            if key.casefold() == diag_group_name.casefold():
                diag_detected = True
                break

        str_print = '|-- ' + diag_group_name + ' '
        if diag_detected:
            str_print += ' yes'.rjust(self._print_tab_len - 1
                                      - str_print.__len__(), '~')
        else:
            str_print += ' no'.rjust(self._print_tab_len - 1
                                     - str_print.__len__(), '~')

        print(str_print)

        if silent:
            sys.stdout = sys.__stdout__

        return diag_detected

    def exist_msi_diagnostics_all(self, silent=False):
        """
            Check for all pre-defined MSI Diagnostic groups.

            Pre-defined diagnostic group are set in
            self._msi_diagnostic_groups,

            :param silent:
            :return:
        """
        all_diags_exist = False

        for ii, diag in enumerate(self._msi_diagnostic_groups):
            status = self.exist_msi_diagnostic(diag, silent=silent)

            if ii == 0:
                all_diags_exist = status
            else:
                all_diags_exist = (all_diags_exist and status)

        return all_diags_exist, self._msi_diagnostic_groups

    def check_data_group(self, silent=False):
        """
            Check for the existence of the 'Raw data + config' Group.

            :param silent:
            :return:
        """
        if silent:
            sys.stdout = open(os.devnull, 'w')

        data_detected = False
        for key in self._hdf_obj.keys():
            if key.casefold() == self._data_group.casefold():
                data_detected = True

        str_print = self._data_group + '/ '
        if data_detected:
            str_print += ' yes'.rjust(self._print_tab_len - 1
                                      - str_print.__len__(), '~')
        else:
            str_print += 'no'.rjust(self._print_tab_len - 1
                                    - str_print.__len__(), '~')

        if silent:
            sys.stdout = sys.__stdout__

        print(str_print)
