"""
Module for the LeCroy (Physics 180E) digitizer mapper
`~bapsflib._hdf.maps.digitizers.lecroy.HDFMapDigiLeCroy180E`.
"""

__all__ = ["HDFMapDigiLeCroy180E"]

import h5py
import numpy as np

from typing import Any, Dict, List, Optional, Tuple
from warnings import warn

from bapsflib._hdf.maps.digitizers.templates import HDFMapDigiTemplate
from bapsflib.utils.exceptions import HDFMappingError
from bapsflib.utils.warnings import HDFMappingWarning


class HDFMapDigiLeCroy180E(HDFMapDigiTemplate):
    """
    Mapping class for the 'LeCroy_scope' digitizer moduler used in the
    Physics 180E Lab.

    Simple group structure looks like:

    .. code-block:: none

        +-- LeCroy_scope
        |   +-- Channel1
        |   +-- Channel2
        |   +-- Channel3
        |   +-- Channel4
        |   +-- Headers
        |   |   +-- Channel1
        |   |   +-- Channel2
        |   |   +-- Channel3
        |   |   +-- Channel4
        |   +-- LeCroy_scope_Setup_Array
        |   +-- time
    """

    _device_adcs = ("lecroy",)

    def deduce_config_active_status(self, config_name: str) -> bool:
        """
        The LeCroy scope only has one configuration that is always named
        `"lecroy"`.

        Parameters
        ----------
        config_name : str
            Configuration name to compare the active configurations.
            ONLY active configuration is ``"lecroy"``.

        Returns
        -------
        bool
            `True` if ``config_name`` equals ``"lecroy"``, otherwise
            `False`.
        """
        return config_name == "lecroy"

    def _find_adc_connections(
        self,
    ) -> Tuple[Tuple[int, Tuple[int, ...], Dict[str, Any]], ...]:
        """
        Determines active connections on the adc.

        Returns
        -------
        tuple
            Tuple of 3-element tuples where the 1st element of the
            nested tuple represents a connected *board* number, the 2nd
            element is a tuple of connected *channel* numbers for the
            *board*, and the 3rd element is a dictionary of adc setup
            values (*bit*, *clock rate*, etc.).
        """
        config_group = self.group

        # initialize conn, brd, and chs
        # conn = list of connections
        # brd  = board number
        # chs  = list of connect channels of board brd
        #
        conn = []

        # Determine active channels
        chs = []
        for ch, ch_dset_name in zip(
            [1, 2, 3, 4], ["Channel1", "Channel2", "Channel3", "Channel4"]
        ):
            if ch_dset_name not in config_group:
                # channel dataset does not exist
                continue

            if ch_dset_name not in config_group["Headers"]:
                # channel header dataset does not exist
                continue

            dset = config_group[ch_dset_name]
            if not isinstance(dset, h5py.Dataset):
                continue

            if "recorded" in dset.attrs and bool(dset.attrs["recorded"]) is False:
                # channel dataset is present but data was not recorded to it
                continue

            chs.append(ch)

        # board number
        brd = 0

        # build subconn tuple with connected board, channels, and
        # acquisition parameters
        subconn = (brd, tuple(chs), {"bit": None, "clock rate": None})

        # add to all connections list
        conn.append(subconn)

        return tuple(conn)

    def _adc_info_first_pass(
        self,
    ) -> Tuple[Tuple[int, Tuple[int, ...], Dict[str, Any]], ...]:

        # 'Acquisition/LeCroy_scope' group has only one possible
        # adc ('lecroy')
        # adc_info = (
        #     int, # board number
        #     (int, ...), # connected channel numbers
        #     {'bit': 14, # bit resolution
        #      'clock rate': <Quantity 100.0 MHz>,
        #      'nshotnum': int,
        #      'shot average (software)': int,
        #      'sample average (hardware)': int})
        #
        # conns is a tuple of tuples where each tuple is a seed for the
        # elements of `adc_info`
        conns = self._find_adc_connections()
        conns[0][2]["shot average (software)"] = None
        conns[0][2]["sample average (hardware)"] = None

        adc_info = () if len(conns[0][1]) == 0 else (conns[0],)
        return adc_info

    def _adc_info_second_pass(
        self,
    ) -> Tuple[Tuple[int, Tuple[int, ...], Dict[str, Any]], ...]:
        """
        Reviews and updates the `adc_info` originally generated by
        :meth:`_adc_info_first_pass`.

        Returns
        -------
        tuple
            Tuple of 3-element tuples where the 1st element of the
            nested tuple represents a connected *board* number, the 2nd
            element is a tuple of connected *channel* numbers for the
            *board*, and the 3rd element is a dictionary of adc setup
            values (*bit*, *clock rate*, etc.).

        Notes
        -----

        On the second pass, the main and header dataset associated with
        each board number and channel number is reviewed.  The
        meta-info dict is then updated with:

        .. csv-table::
            :header: "Key", "Description"
            :widths: 20, 60

            "::

                'nshotnum'
            ", "
            the number of shot numbers contained in the datasets
            associated with a **board**, equivalent to
            ``dset.shape[0]``
            "
            "::

                'nt'
            ", "
            the number of time samples recorded in the datasets
            associated with a **board**, equivalent to
            ``dset.shape[1]``
            "
        """
        # ensure dataset exists for each (brd, ch) combo
        # - remove (brd, ch) combos if dataset does not exist
        # - remove brd entry if chs are NULL
        # populate 'nshotnum' and 'nt' for each board
        # - confirm all associated channels have matching shape
        # - if not, then define nshotnum = 0 and nt = 0 and warn
        #
        # get conns
        config_name = "lecroy"
        adc_name = "lecroy"
        conn = self.configs[config_name][adc_name][0]
        board = conn[0]
        channels = conn[1]  # type: List[int]

        # get 'nshotnum', 'nt', and 'channel_labels' values
        new_chs = list(channels)
        chs_to_remove = []
        ch_labels = []
        nshotnum = None
        nt = None
        for ch in new_chs:
            # -- examine dataset --
            dset_name = self.construct_dataset_name(board, ch)  # type: str
            dset = self.group[dset_name]  # type: h5py.Dataset

            # dataset should not have fields
            if dset.dtype.names is not None:
                warn(
                    f"HDF5 structure unexpected...dataset '{dset_name}' has "
                    f"fields...not adding to `configs` dict",
                    HDFMappingWarning,
                )
                chs_to_remove.append(ch)
                continue

            # dataset should be a 2D array
            if len(dset.shape) != 2:
                # dataset not 2D array
                warn(
                    f"HDF5 structure unexpected...dataset '{dset_name}' is "
                    f"NOT a 2D array...not adding to `configs` dict",
                    HDFMappingWarning,
                )
                chs_to_remove.append(ch)
                continue

            # Define and check nt
            # - should be consistent across all datasets
            if nt is None:
                nt = dset.shape[1]
            elif nt == -1:
                pass
            else:
                if nt != dset.shape[1]:
                    warn(
                        f"HDF5 structure unexpected...number of time "
                        f"sample inconsistent across all channels for "
                        f"board {board}...setting nt = -1",
                        HDFMappingWarning,
                    )
                    nt = -1
                    continue

            # Define and check nshotnum
            # - should be consistent across all datasets
            if nshotnum is None:
                nshotnum = dset.shape[0]
            elif nshotnum == -1:
                pass
            else:
                if nshotnum != dset.shape[0]:
                    warn(
                        f"HDF5 structure unexpected...number of shot "
                        f"numbers inconsistent across all channels for "
                        f"board {board}...setting nshotnum = -1",
                        HDFMappingWarning,
                    )
                    nshotnum = -1
                    continue

            # -- examine header dataset --
            hdset_name = self.construct_header_dataset_name(board, ch)
            hdset = self.group[hdset_name]

            # header dataset and digitizer dataset need to have the same number
            # of rows
            if hdset.shape != (nshotnum,):
                warn(
                    f"HDF5 structure unexpected...dataset and header "
                    f"dataset for board {board} and channel {ch} do NOT have "
                    f"the same number of shot numbers...not adding to "
                    f"`configs` dict",
                    HDFMappingWarning,
                )
                chs_to_remove.append(ch)
                continue

            # get channel labels
            ch_labels.append(dset.attrs.get("description", default=""))

        # ensure chs is not NULL
        for ch in chs_to_remove:
            new_chs.remove(ch)
        if len(new_chs) == 0:
            raise HDFMappingError(
                self.info["group path"],
                why=(
                    f"HDF5 structure unexpected...'Board number {board}' does not "
                    f"define any valid channel numbers...not adding to "
                    f"`configs` dict"
                ),
            )

        # add nshotnum and nt to setup dict
        conn[2].update(
            {
                "nshotnum": nshotnum,
                "nt": nt,
                "channel_labels": tuple(ch_labels),
            }
        )
        # append new_conns
        new_conns = ((board, tuple(new_chs), conn[2]),)

        return tuple(new_conns)

    def _build_configs(self):
        """Builds the :attr:`configs` dictionary."""
        # collect names of datasets and sub-groups
        subgroup_names = []
        dataset_names = []
        for key in self.group.keys():
            if isinstance(self.group[key], h5py.Dataset):
                dataset_names.append(key)
            if isinstance(self.group[key], h5py.Group):
                subgroup_names.append(key)

        if "Headers" not in subgroup_names:
            raise HDFMappingError(
                self.info["group path"],
                why=(
                    "Digitizer is missing the 'Headers' group that "
                    "contains the header datasets."
                ),
            )

        # build self.configs
        #
        # determine configuration name
        # - The 180E setup only uses one configuration per data run,
        #   so a configuration name is not a deployed concept.  For
        #   bapsflib we'll just call the configuration name 'lecroy'.
        config_name = "lecroy"

        # initialize configuration name in the config dict
        # - add 'config group path'
        self._configs[config_name] = {
            "config group path": self.group.name,
        }

        # determine if config is active (it is always active)
        self._configs[config_name]["active"] = self.deduce_config_active_status(
            config_name
        )

        # assign active adc's to the configuration
        self._configs[config_name]["adc"] = self._device_adcs

        # define 'shotnum' entry
        #
        # Note:
        #   A shot number is not recorded for the data runs taken
        #   in the 180E Lab.
        #
        self._configs[config_name]["shotnum"] = None

        # initialize adc info
        self._configs[config_name]["lecroy"] = self._adc_info_first_pass()

        # ensure something is being digitized
        if len(self._configs[config_name]["lecroy"]) == 0:
            raise HDFMappingError(
                self.info["group path"],
                why=(
                    f"HDF5 structure unexpected...The LeCroy digitizer "
                    f"has NO active channels."
                ),
            )

        # update adc info with 'nshotnum' and 'nt'
        # - `construct_dataset_name` needs adc info to be seeded
        # - the following updates depend on construct_dataset_name
        #
        self._configs[config_name]["lecroy"] = self._adc_info_second_pass()

        # update with time information
        if "time" in dataset_names:
            dset_time = self.group["time"]
            nt = self._configs[config_name]["lecroy"][0][2]["nt"]

            if dset_time.ndim != 1 or dset_time.size != nt:
                pass
            else:
                self._configs[config_name]["lecroy"][0][2]["time_dset_path"] = "time"

    def construct_dataset_name(
        self,
        board: int,
        channel: int,
        config_name: str = None,
        adc: str = None,
        return_info: bool = False,
    ) -> str | Tuple[str, Dict[str, Any]]:
        """
        Construct the name of the HDF5 dataset containing digitizer
        data. The dataset name follows the format::

            '<config_name> [<board>:<channel>]'

        where `<config_name>` is the digitizer configuration name,
        `<board>` is the requested board number, and `<channel>` is
        the requested channel number.

        Parameters
        ----------
        board : `int`
            board number

        channel : `int`
            channel number

        config_name : `str`, optional
            digitizer configuration name

        adc : `str`, optional
            analog-digital-converter name

        return_info : `bool`, optional
            `True` will return a dictionary of meta-info associated
            with the digitizer data (DEFAULT `False`)

        Returns
        -------
        str | Tuple[str, Dict[str, Any]]
            digitizer dataset name. If ``return_info=True``, then
            returns a tuple of (dataset name, dictionary of meta-info)

        Notes
        -----
        The returned adc information dictionary looks like::

            adc_dict = {
                'adc': str,
                'bit': int,
                'clock rate': astropy.units.Quantity,
                'configuration name': str,
                'digitizer': str,
                'nshotnum': int,
                'nt': int,
                'sample average (hardware)': int,
                'shot average (software)': int,
            }
        """
        # Condition config_name
        # - if config_name is not specified then the 'active' config
        #   is sought out
        if config_name is None:
            config_name = "lecroy"
        elif config_name != "lecroy":
            raise ValueError(
                f"The only valid `config_name` value is 'lecroy'.  Use 'lecroy' "
                f"or omit optional keyword argument 'config_name'."
            )

        # Condition adc keyword
        if adc is None:
            adc = "lecroy"
        elif adc != "lecroy":
            raise ValueError(
                f"The only valid `adc` value is 'lecroy'.  Use 'lecroy' "
                f"or omit optional keyword argument 'adc'."
            )

        # Condition board
        if board != 0:
            raise ValueError(
                f"The only valid `board` value is '0' (the int zero).  Use 'lecroy' "
                f"or omit optional keyword argument 'adc'."
            )

        # Condition channel
        if channel not in (1, 2, 3, 4):
            raise ValueError(
                f"Got value {channel} for argument `channel`, but only values "
                f"1, 2, 3, or 4 are accepted."
            )

        # search if (board, channel) combo is connected
        bc_valid = False
        d_info = None
        for brd, chs, extras in self._configs[config_name][adc]:
            if channel in chs:
                # board, channel combo valid
                bc_valid = True

                # save adc settings for return if requested
                if return_info:
                    d_info = extras
                    d_info["adc"] = "lecroy"
                    d_info["configuration name"] = config_name
                    d_info["digitizer"] = self._info["group name"]
                break

        # (board, channel) combo must be active
        if not bc_valid:
            raise ValueError(
                "Input `board` and `channel` do NOT specified a valid dataset."
            )

        # checks passed, build dataset_name
        dataset_name = f"Channel{channel}"

        # return
        if return_info:
            return dataset_name, d_info
        else:
            return dataset_name

    def construct_header_dataset_name(
        self, board: int, channel: int, config_name="lecroy", adc="lecroy", **kwargs
    ) -> str:
        """
        Construct the name of the HDF5 header dataset associated with
        the digitizer dataset. The header dataset stores shot numbers
        and other shot number specific meta-data.  It also has a one-
        to-one row correspondence with the digitizer dataset.  The
        header dataset name follows the format::

            'Headers/<dataset name>'

        where `<dataset name>` is the digitizer dataset name specified
        by the input arguments and constructed by
        :meth:`construct_dataset_name`.

        Parameters
        ----------
        board : `int`
            board number

        channel : `int`
            channel number

        config_name : `str`, optional
            digitizer configuration name

        adc : `str`, optional
            analog-digital-converter name

        Returns
        -------
        str
            header dataset name associated with the digitizer dataset
        """
        # ensure return_info kwarg is always False
        kwargs["return_info"] = False

        # get dataset name
        dset_name = self.construct_dataset_name(
            board, channel, config_name=config_name, adc=adc, **kwargs
        )

        # build and return header name
        dheader_name = f"Headers/{dset_name}"
        return dheader_name
