"""
Sub-package defining the high-level interface to access and read data
written in the HDF5 files generated by devices in the UCLA Physics 180E
class.
"""

__all__ = ["File"]

from bapsflib.phys180E._hdf.file_ import File
