# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFile = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFile.sizePolicy().hasHeightForWidth())
        self.labelFile.setSizePolicy(sizePolicy)
        self.labelFile.setTextFormat(QtCore.Qt.PlainText)
        self.labelFile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelFile.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelFile.setObjectName("labelFile")
        self.horizontalLayout.addWidget(self.labelFile)
        self.textFilenameContainer = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textFilenameContainer.sizePolicy().hasHeightForWidth())
        self.textFilenameContainer.setSizePolicy(sizePolicy)
        self.textFilenameContainer.setMinimumSize(QtCore.QSize(0, 21))
        self.textFilenameContainer.setMaximumSize(QtCore.QSize(16777215, 31))
        self.textFilenameContainer.setBaseSize(QtCore.QSize(0, 0))
        self.textFilenameContainer.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textFilenameContainer.setMouseTracking(True)
        self.textFilenameContainer.setAcceptDrops(False)
        self.textFilenameContainer.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textFilenameContainer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textFilenameContainer.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textFilenameContainer.setUndoRedoEnabled(False)
        self.textFilenameContainer.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textFilenameContainer.setReadOnly(True)
        self.textFilenameContainer.setObjectName("textFilenameContainer")
        self.horizontalLayout.addWidget(self.textFilenameContainer)
        self.pushOpenHDF = QtWidgets.QPushButton(self.centralwidget)
        self.pushOpenHDF.setAutoExclusive(False)
        self.pushOpenHDF.setObjectName("pushOpenHDF")
        self.horizontalLayout.addWidget(self.pushOpenHDF)
        self.pushClear = QtWidgets.QPushButton(self.centralwidget)
        self.pushClear.setObjectName("pushClear")
        self.horizontalLayout.addWidget(self.pushClear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitterLV = QtWidgets.QSplitter(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterLV.sizePolicy().hasHeightForWidth())
        self.splitterLV.setSizePolicy(sizePolicy)
        self.splitterLV.setMinimumSize(QtCore.QSize(220, 0))
        self.splitterLV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitterLV.setOrientation(QtCore.Qt.Vertical)
        self.splitterLV.setObjectName("splitterLV")
        self.tabWidget = QtWidgets.QTabWidget(self.splitterLV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTree = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabTree.sizePolicy().hasHeightForWidth())
        self.tabTree.setSizePolicy(sizePolicy)
        self.tabTree.setMinimumSize(QtCore.QSize(0, 0))
        self.tabTree.setObjectName("tabTree")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabTree)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeView = QtWidgets.QTreeView(self.tabTree)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMouseTracking(True)
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView.setSortingEnabled(True)
        self.treeView.setHeaderHidden(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(False)
        self.treeView.header().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.treeView)
        self.tabWidget.addTab(self.tabTree, "")
        self.tabMSI = QtWidgets.QWidget()
        self.tabMSI.setObjectName("tabMSI")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabMSI)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.tabMSI)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.pageDischarge = QtWidgets.QWidget()
        self.pageDischarge.setGeometry(QtCore.QRect(0, 0, 256, 365))
        self.pageDischarge.setObjectName("pageDischarge")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageDischarge)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.toolBox.addItem(self.pageDischarge, "")
        self.pageGasPressure = QtWidgets.QWidget()
        self.pageGasPressure.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pageGasPressure.setObjectName("pageGasPressure")
        self.toolBox.addItem(self.pageGasPressure, "")
        self.pageHeater = QtWidgets.QWidget()
        self.pageHeater.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pageHeater.setObjectName("pageHeater")
        self.toolBox.addItem(self.pageHeater, "")
        self.pageInterferometer = QtWidgets.QWidget()
        self.pageInterferometer.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pageInterferometer.setObjectName("pageInterferometer")
        self.toolBox.addItem(self.pageInterferometer, "")
        self.pageMagneticField = QtWidgets.QWidget()
        self.pageMagneticField.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.pageMagneticField.setObjectName("pageMagneticField")
        self.toolBox.addItem(self.pageMagneticField, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tabMSI, "")
        self.framePlotConfig = QtWidgets.QFrame(self.splitterLV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.framePlotConfig.sizePolicy().hasHeightForWidth())
        self.framePlotConfig.setSizePolicy(sizePolicy)
        self.framePlotConfig.setStyleSheet(".QFrame{\n"
"    border: 1px solid grey;\n"
"    border-radius: 6px;\n"
"}")
        self.framePlotConfig.setFrameShape(QtWidgets.QFrame.Box)
        self.framePlotConfig.setObjectName("framePlotConfig")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.framePlotConfig)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.framePlotConfig)
        self.label.setLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.widgetInfoDisplay = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetInfoDisplay.sizePolicy().hasHeightForWidth())
        self.widgetInfoDisplay.setSizePolicy(sizePolicy)
        self.widgetInfoDisplay.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetInfoDisplay.setObjectName("widgetInfoDisplay")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetInfoDisplay)
        self.verticalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.labelRootParent = QtWidgets.QLabel(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRootParent.sizePolicy().hasHeightForWidth())
        self.labelRootParent.setSizePolicy(sizePolicy)
        self.labelRootParent.setMinimumSize(QtCore.QSize(0, 0))
        self.labelRootParent.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelRootParent.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.labelRootParent.setObjectName("labelRootParent")
        self.verticalLayout_2.addWidget(self.labelRootParent)
        self.line_1 = QtWidgets.QFrame(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_1.sizePolicy().hasHeightForWidth())
        self.line_1.setSizePolicy(sizePolicy)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_2.addWidget(self.line_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSelectedItem = QtWidgets.QLabel(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSelectedItem.sizePolicy().hasHeightForWidth())
        self.labelSelectedItem.setSizePolicy(sizePolicy)
        self.labelSelectedItem.setMinimumSize(QtCore.QSize(0, 0))
        self.labelSelectedItem.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelSelectedItem.setMouseTracking(True)
        self.labelSelectedItem.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.labelSelectedItem.setObjectName("labelSelectedItem")
        self.horizontalLayout_2.addWidget(self.labelSelectedItem)
        self.labelShowRows = QtWidgets.QLabel(self.widgetInfoDisplay)
        self.labelShowRows.setMinimumSize(QtCore.QSize(0, 0))
        self.labelShowRows.setIndent(30)
        self.labelShowRows.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelShowRows.setObjectName("labelShowRows")
        self.horizontalLayout_2.addWidget(self.labelShowRows)
        self.cboxStartRow = QtWidgets.QComboBox(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboxStartRow.sizePolicy().hasHeightForWidth())
        self.cboxStartRow.setSizePolicy(sizePolicy)
        self.cboxStartRow.setMinimumSize(QtCore.QSize(0, 0))
        self.cboxStartRow.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cboxStartRow.setEditable(True)
        self.cboxStartRow.setObjectName("cboxStartRow")
        self.horizontalLayout_2.addWidget(self.cboxStartRow)
        self.labelTo = QtWidgets.QLabel(self.widgetInfoDisplay)
        self.labelTo.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTo.setObjectName("labelTo")
        self.horizontalLayout_2.addWidget(self.labelTo)
        self.cboxStopRow = QtWidgets.QComboBox(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboxStopRow.sizePolicy().hasHeightForWidth())
        self.cboxStopRow.setSizePolicy(sizePolicy)
        self.cboxStopRow.setMinimumSize(QtCore.QSize(0, 0))
        self.cboxStopRow.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cboxStopRow.setEditable(True)
        self.cboxStopRow.setObjectName("cboxStopRow")
        self.horizontalLayout_2.addWidget(self.cboxStopRow)
        self.btnDisplayDataTable = QtWidgets.QPushButton(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisplayDataTable.sizePolicy().hasHeightForWidth())
        self.btnDisplayDataTable.setSizePolicy(sizePolicy)
        self.btnDisplayDataTable.setMinimumSize(QtCore.QSize(0, 0))
        self.btnDisplayDataTable.setObjectName("btnDisplayDataTable")
        self.horizontalLayout_2.addWidget(self.btnDisplayDataTable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitterRV = QtWidgets.QSplitter(self.widgetInfoDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterRV.sizePolicy().hasHeightForWidth())
        self.splitterRV.setSizePolicy(sizePolicy)
        self.splitterRV.setOrientation(QtCore.Qt.Vertical)
        self.splitterRV.setObjectName("splitterRV")
        self.widgetItemAttr = QtWidgets.QWidget(self.splitterRV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetItemAttr.sizePolicy().hasHeightForWidth())
        self.widgetItemAttr.setSizePolicy(sizePolicy)
        self.widgetItemAttr.setMinimumSize(QtCore.QSize(0, 1))
        self.widgetItemAttr.setObjectName("widgetItemAttr")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetItemAttr)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textItemGeneral = QtWidgets.QTextBrowser(self.widgetItemAttr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textItemGeneral.sizePolicy().hasHeightForWidth())
        self.textItemGeneral.setSizePolicy(sizePolicy)
        self.textItemGeneral.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textItemGeneral.setPalette(palette)
        self.textItemGeneral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textItemGeneral.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textItemGeneral.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textItemGeneral.setObjectName("textItemGeneral")
        self.horizontalLayout_4.addWidget(self.textItemGeneral)
        self.tableItemAttr = QtWidgets.QTableView(self.widgetItemAttr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableItemAttr.sizePolicy().hasHeightForWidth())
        self.tableItemAttr.setSizePolicy(sizePolicy)
        self.tableItemAttr.setMinimumSize(QtCore.QSize(0, 0))
        self.tableItemAttr.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tableItemAttr.setMouseTracking(True)
        self.tableItemAttr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableItemAttr.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableItemAttr.setObjectName("tableItemAttr")
        self.tableItemAttr.horizontalHeader().setVisible(False)
        self.tableItemAttr.verticalHeader().setVisible(False)
        self.tableItemAttr.verticalHeader().setDefaultSectionSize(30)
        self.horizontalLayout_4.addWidget(self.tableItemAttr)
        self.scrollAreaDataDisplay = QtWidgets.QScrollArea(self.splitterRV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollAreaDataDisplay.sizePolicy().hasHeightForWidth())
        self.scrollAreaDataDisplay.setSizePolicy(sizePolicy)
        self.scrollAreaDataDisplay.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaDataDisplay.setStyleSheet(".QScrollArea{border: 1px solid grey}")
        self.scrollAreaDataDisplay.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaDataDisplay.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollAreaDataDisplay.setWidgetResizable(True)
        self.scrollAreaDataDisplay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollAreaDataDisplay.setObjectName("scrollAreaDataDisplay")
        self.scrollAreaDataDisplayContents = QtWidgets.QWidget()
        self.scrollAreaDataDisplayContents.setGeometry(QtCore.QRect(0, 0, 689, 287))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaDataDisplayContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaDataDisplayContents.setSizePolicy(sizePolicy)
        self.scrollAreaDataDisplayContents.setObjectName("scrollAreaDataDisplayContents")
        self.scrollAreaDataDisplay.setWidget(self.scrollAreaDataDisplayContents)
        self.verticalLayout_2.addWidget(self.splitterRV)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_HDF5 = QtWidgets.QAction(MainWindow)
        self.actionOpen_HDF5.setObjectName("actionOpen_HDF5")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen_HDF5)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelFile.setText(_translate("MainWindow", "File:"))
        self.textFilenameContainer.setPlaceholderText(_translate("MainWindow", "HDF5 file"))
        self.pushOpenHDF.setText(_translate("MainWindow", "Open"))
        self.pushClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTree), _translate("MainWindow", "HDF Tree"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageDischarge), _translate("MainWindow", "Discharge"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageGasPressure), _translate("MainWindow", "Gas Pressure"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageHeater), _translate("MainWindow", "Heater"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageInterferometer), _translate("MainWindow", "Interferometer"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageMagneticField), _translate("MainWindow", "Magnetic Field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMSI), _translate("MainWindow", "MSI Plot Selector"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Plot Configurator</span></p></body></html>"))
        self.labelRootParent.setText(_translate("MainWindow", "Root Parent"))
        self.labelSelectedItem.setText(_translate("MainWindow", "Item Selected"))
        self.labelShowRows.setText(_translate("MainWindow", "Show Rows:"))
        self.labelTo.setText(_translate("MainWindow", "to"))
        self.btnDisplayDataTable.setText(_translate("MainWindow", "Table"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_HDF5.setText(_translate("MainWindow", "Open HDF5"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

