# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/wdgSimplePlotConfig.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formPlotConfig(object):
    def setupUi(self, formPlotConfig):
        formPlotConfig.setObjectName("formPlotConfig")
        formPlotConfig.resize(500, 634)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(formPlotConfig.sizePolicy().hasHeightForWidth())
        formPlotConfig.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(formPlotConfig)
        self.verticalLayout.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelDataRows = QtWidgets.QLabel(formPlotConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDataRows.sizePolicy().hasHeightForWidth())
        self.labelDataRows.setSizePolicy(sizePolicy)
        self.labelDataRows.setIndent(10)
        self.labelDataRows.setObjectName("labelDataRows")
        self.horizontalLayout_2.addWidget(self.labelDataRows)
        self.cboxPlotRow = QtWidgets.QComboBox(formPlotConfig)
        self.cboxPlotRow.setEditable(True)
        self.cboxPlotRow.setObjectName("cboxPlotRow")
        self.horizontalLayout_2.addWidget(self.cboxPlotRow)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupXSettings = QtWidgets.QGroupBox(formPlotConfig)
        self.groupXSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.groupXSettings.setObjectName("groupXSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupXSettings)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupXSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setIndent(4)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cboxXAxes = QtWidgets.QComboBox(self.groupXSettings)
        self.cboxXAxes.setEditable(True)
        self.cboxXAxes.setObjectName("cboxXAxes")
        self.horizontalLayout_3.addWidget(self.cboxXAxes)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.btnXAxisTitleReset = QtWidgets.QPushButton(self.groupXSettings)
        self.btnXAxisTitleReset.setObjectName("btnXAxisTitleReset")
        self.gridLayout.addWidget(self.btnXAxisTitleReset, 0, 3, 1, 1)
        self.labelXScale = QtWidgets.QLabel(self.groupXSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXScale.sizePolicy().hasHeightForWidth())
        self.labelXScale.setSizePolicy(sizePolicy)
        self.labelXScale.setIndent(4)
        self.labelXScale.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelXScale.setObjectName("labelXScale")
        self.gridLayout.addWidget(self.labelXScale, 1, 0, 1, 1)
        self.labelXTitle = QtWidgets.QLabel(self.groupXSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelXTitle.sizePolicy().hasHeightForWidth())
        self.labelXTitle.setSizePolicy(sizePolicy)
        self.labelXTitle.setIndent(4)
        self.labelXTitle.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelXTitle.setObjectName("labelXTitle")
        self.gridLayout.addWidget(self.labelXTitle, 0, 0, 1, 1)
        self.txtXAxisScale = QtWidgets.QLineEdit(self.groupXSettings)
        self.txtXAxisScale.setObjectName("txtXAxisScale")
        self.gridLayout.addWidget(self.txtXAxisScale, 1, 1, 1, 1)
        self.txtXAxisTitle = QtWidgets.QLineEdit(self.groupXSettings)
        self.txtXAxisTitle.setObjectName("txtXAxisTitle")
        self.gridLayout.addWidget(self.txtXAxisTitle, 0, 1, 1, 1)
        self.btnXAxisScaleReset = QtWidgets.QPushButton(self.groupXSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXAxisScaleReset.sizePolicy().hasHeightForWidth())
        self.btnXAxisScaleReset.setSizePolicy(sizePolicy)
        self.btnXAxisScaleReset.setObjectName("btnXAxisScaleReset")
        self.gridLayout.addWidget(self.btnXAxisScaleReset, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupXSettings)
        self.groupYSettings = QtWidgets.QGroupBox(formPlotConfig)
        self.groupYSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.groupYSettings.setObjectName("groupYSettings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupYSettings)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupYSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setIndent(4)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cboxYAxes = QtWidgets.QComboBox(self.groupYSettings)
        self.cboxYAxes.setEditable(True)
        self.cboxYAxes.setObjectName("cboxYAxes")
        self.horizontalLayout_4.addWidget(self.cboxYAxes)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtYAxisScale = QtWidgets.QLineEdit(self.groupYSettings)
        self.txtYAxisScale.setObjectName("txtYAxisScale")
        self.gridLayout_2.addWidget(self.txtYAxisScale, 1, 1, 1, 1)
        self.labelYTitle = QtWidgets.QLabel(self.groupYSettings)
        self.labelYTitle.setIndent(4)
        self.labelYTitle.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelYTitle.setObjectName("labelYTitle")
        self.gridLayout_2.addWidget(self.labelYTitle, 0, 0, 1, 1)
        self.txtYAxisTitle = QtWidgets.QLineEdit(self.groupYSettings)
        self.txtYAxisTitle.setObjectName("txtYAxisTitle")
        self.gridLayout_2.addWidget(self.txtYAxisTitle, 0, 1, 1, 1)
        self.labelYScale = QtWidgets.QLabel(self.groupYSettings)
        self.labelYScale.setIndent(4)
        self.labelYScale.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelYScale.setObjectName("labelYScale")
        self.gridLayout_2.addWidget(self.labelYScale, 1, 0, 1, 1)
        self.btnYAxisTitleReset = QtWidgets.QPushButton(self.groupYSettings)
        self.btnYAxisTitleReset.setObjectName("btnYAxisTitleReset")
        self.gridLayout_2.addWidget(self.btnYAxisTitleReset, 0, 2, 1, 1)
        self.btnYAxisScaleReset = QtWidgets.QPushButton(self.groupYSettings)
        self.btnYAxisScaleReset.setObjectName("btnYAxisScaleReset")
        self.gridLayout_2.addWidget(self.btnYAxisScaleReset, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.groupYSettings)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPlot = QtWidgets.QPushButton(formPlotConfig)
        self.btnPlot.setObjectName("btnPlot")
        self.horizontalLayout.addWidget(self.btnPlot)
        spacerItem5 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnPlotSettings = QtWidgets.QPushButton(formPlotConfig)
        self.btnPlotSettings.setObjectName("btnPlotSettings")
        self.horizontalLayout.addWidget(self.btnPlotSettings)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(formPlotConfig)
        QtCore.QMetaObject.connectSlotsByName(formPlotConfig)

    def retranslateUi(self, formPlotConfig):
        _translate = QtCore.QCoreApplication.translate
        formPlotConfig.setWindowTitle(_translate("formPlotConfig", "Form"))
        self.labelDataRows.setText(_translate("formPlotConfig", "Data Row:"))
        self.groupXSettings.setTitle(_translate("formPlotConfig", "X-Axis Settings"))
        self.label.setText(_translate("formPlotConfig", "Select Axis:"))
        self.btnXAxisTitleReset.setText(_translate("formPlotConfig", "Reset"))
        self.labelXScale.setText(_translate("formPlotConfig", "Scale:"))
        self.labelXTitle.setText(_translate("formPlotConfig", "Title:"))
        self.btnXAxisScaleReset.setText(_translate("formPlotConfig", "Reset"))
        self.groupYSettings.setTitle(_translate("formPlotConfig", "Y-Axis Settings"))
        self.label_2.setText(_translate("formPlotConfig", "Select Axis:"))
        self.labelYTitle.setText(_translate("formPlotConfig", "Title:"))
        self.labelYScale.setText(_translate("formPlotConfig", "Scale:"))
        self.btnYAxisTitleReset.setText(_translate("formPlotConfig", "Reset"))
        self.btnYAxisScaleReset.setText(_translate("formPlotConfig", "Reset"))
        self.btnPlot.setText(_translate("formPlotConfig", "Plot"))
        self.btnPlotSettings.setText(_translate("formPlotConfig", "More Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formPlotConfig = QtWidgets.QWidget()
    ui = Ui_formPlotConfig()
    ui.setupUi(formPlotConfig)
    formPlotConfig.show()
    sys.exit(app.exec_())

