# This file is part of the bapsflib package, a Python toolkit for the
# BaPSF group at UCLA.
#
# http://plasma.physics.ucla.edu/
#
# Copyright 2017-2018 Erik T. Everson and contributors
#
# License: Standard 3-clause BSD; see "LICENSES/LICENSE.txt" for full
#   license terms and contributor agreement.
#
"""
The :mod:`bapsflib.lapd` module contains the necessary tools to
open (:class:`~bapsflib.lapd.files.File`),
map (:class:`~bapsflib.lapd.hdfmapper.hdfMap`),
check, (:class:`~bapsflib.lapd.hdfoverview.hdfOverview`)
and read out (:meth:`~bapsflib.lapd.files.File.read_data` and
:meth:`~bapsflib.lapd.files.File.read_controls`)
data written into HDF5 files generated by the LaPD DAQ system.
"""
from bapsflib.lapd._hdf.files import File
