name: Check PR Change Log

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  changelog_checker:
    # the gilesbot configuration is defined in pyproject.toml
    name: Check for 'towncrier' Change Log Entries
    runs-on: ubuntu-latest
    steps:
      - name: play
        run: |
          echo "do something"
      - name: Look for change log entry
        uses: pllim/actions-towncrier-changelog@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_USERNAME: gilesbot
